use_frameworks!

platform :ios, '13.0'

target 'UPsKit_Example' do
  
  pod 'UPsKit', :path => '../'
  
  pod 'RxCocoa', '~> 6'
  pod 'RxSwift', '~> 6'
  pod 'SnapKit', '~> 5'
  pod 'Then', '~> 3'
  
  target 'UPsKit_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    end
  end
end
